apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyoa
  labels:
    app: cyoa
    chart: cyoa
    release: some-name
    heritage: Helm
    protocol: http
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cyoa
      release: some-name
      protocol: http

  template:
    metadata:
      labels:
        app: cyoa
        release: some-name
        protocol: http
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: localcopy-labels-http
          image: "/cyoa:latest"
          command: ["/cyoa", "-f", "/templates/story.json"]
#          args: ["http"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 500MB
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10