apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyoa
  labels:
    app: cyoa
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cyoa
  template:
    metadata:
      labels:
        app: cyoa
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: cyoa
          image: "sasulka/cyoatest:1.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 0.5Gi
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10